// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package gensql

import (
	"context"
)

type Querier interface {
	GetCost(ctx context.Context) ([]*Cost, error)
}

var _ Querier = (*Queries)(nil)
