// Code generated by mockery. DO NOT EDIT.

package resourceusage

import (
	context "context"

	model "github.com/nais/console-backend/internal/graph/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// UtilizationForApp provides a mock function with given fields: ctx, resource, env, team, app, start, end
func (_m *MockClient) UtilizationForApp(ctx context.Context, resource model.ResourceType, env string, team string, app string, start time.Time, end time.Time) ([]model.ResourceUtilization, error) {
	ret := _m.Called(ctx, resource, env, team, app, start, end)

	var r0 []model.ResourceUtilization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ResourceType, string, string, string, time.Time, time.Time) ([]model.ResourceUtilization, error)); ok {
		return rf(ctx, resource, env, team, app, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ResourceType, string, string, string, time.Time, time.Time) []model.ResourceUtilization); ok {
		r0 = rf(ctx, resource, env, team, app, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ResourceUtilization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ResourceType, string, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, resource, env, team, app, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_UtilizationForApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UtilizationForApp'
type MockClient_UtilizationForApp_Call struct {
	*mock.Call
}

// UtilizationForApp is a helper method to define mock.On call
//   - ctx context.Context
//   - resource model.ResourceType
//   - env string
//   - team string
//   - app string
//   - start time.Time
//   - end time.Time
func (_e *MockClient_Expecter) UtilizationForApp(ctx interface{}, resource interface{}, env interface{}, team interface{}, app interface{}, start interface{}, end interface{}) *MockClient_UtilizationForApp_Call {
	return &MockClient_UtilizationForApp_Call{Call: _e.mock.On("UtilizationForApp", ctx, resource, env, team, app, start, end)}
}

func (_c *MockClient_UtilizationForApp_Call) Run(run func(ctx context.Context, resource model.ResourceType, env string, team string, app string, start time.Time, end time.Time)) *MockClient_UtilizationForApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ResourceType), args[2].(string), args[3].(string), args[4].(string), args[5].(time.Time), args[6].(time.Time))
	})
	return _c
}

func (_c *MockClient_UtilizationForApp_Call) Return(_a0 []model.ResourceUtilization, _a1 error) *MockClient_UtilizationForApp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_UtilizationForApp_Call) RunAndReturn(run func(context.Context, model.ResourceType, string, string, string, time.Time, time.Time) ([]model.ResourceUtilization, error)) *MockClient_UtilizationForApp_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
