version: "3.1"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: console
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"

  bigquery:
    image: ghcr.io/goccy/bigquery-emulator:latest
    command: ["bigquery-emulator", "--project=project", "--dataset=dataset", "--data-from-yaml=/data.yaml"]
    ports:
      - "9050:9050"
    volumes:
        - ./data/bigquery-emulator-data.yaml:/data.yaml

volumes:
  db-data:
