version: "3.1"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: console
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  db-data:
