// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package gensql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cost struct {
	Env                *string
	Team               *string
	App                *string
	ServiceDescription string
	Date               pgtype.Date
	Cost               float32
}
