// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: resourceusage.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const maxResourceUtilizationDate = `-- name: MaxResourceUtilizationDate :one
SELECT MAX(timestamp)::timestamptz FROM resource_utilization_metrics
`

// MaxResourceUtilizationDate will return the max date for resource utilization records.
func (q *Queries) MaxResourceUtilizationDate(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, maxResourceUtilizationDate)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const resourceUtilizationDateRange = `-- name: ResourceUtilizationDateRange :one
SELECT
    MIN(timestamp)::timestamptz AS "from",
    MAX(timestamp)::timestamptz AS "to"
FROM
    resource_utilization_metrics
WHERE
    env = $1
    AND team = $2
    AND name = $3
    AND kind = $4
`

type ResourceUtilizationDateRangeParams struct {
	Env  string
	Team string
	Name string
	Kind Kind
}

type ResourceUtilizationDateRangeRow struct {
	From pgtype.Timestamptz
	To   pgtype.Timestamptz
}

// ResourceUtilizationDateRange will return the min and max timestamps for an app/job.
func (q *Queries) ResourceUtilizationDateRange(ctx context.Context, arg ResourceUtilizationDateRangeParams) (*ResourceUtilizationDateRangeRow, error) {
	row := q.db.QueryRow(ctx, resourceUtilizationDateRange,
		arg.Env,
		arg.Team,
		arg.Name,
		arg.Kind,
	)
	var i ResourceUtilizationDateRangeRow
	err := row.Scan(&i.From, &i.To)
	return &i, err
}

const resourceUtilizationDateRangeForTeam = `-- name: ResourceUtilizationDateRangeForTeam :one
SELECT
    MIN(timestamp)::timestamptz AS "from",
    MAX(timestamp)::timestamptz AS "to"
FROM
    resource_utilization_metrics
WHERE
    team = $1
`

type ResourceUtilizationDateRangeForTeamRow struct {
	From pgtype.Timestamptz
	To   pgtype.Timestamptz
}

// ResourceUtilizationDateRangeForTeam will return the min and max timestamps for a specific team.
func (q *Queries) ResourceUtilizationDateRangeForTeam(ctx context.Context, team string) (*ResourceUtilizationDateRangeForTeamRow, error) {
	row := q.db.QueryRow(ctx, resourceUtilizationDateRangeForTeam, team)
	var i ResourceUtilizationDateRangeForTeamRow
	err := row.Scan(&i.From, &i.To)
	return &i, err
}

const resourceUtilizationForApp = `-- name: ResourceUtilizationForApp :many
SELECT
    id, timestamp, env, team, name, kind, resource_type, usage, request
FROM
    resource_utilization_metrics
WHERE
    env = $1
    AND team = $2
    AND name = $3
    AND kind = $4
    AND resource_type = $5
    AND timestamp >= $6::timestamptz
    AND timestamp < $7::timestamptz
ORDER BY
    timestamp ASC
`

type ResourceUtilizationForAppParams struct {
	Env          string
	Team         string
	Name         string
	Kind         Kind
	ResourceType ResourceType
	Start        pgtype.Timestamptz
	End          pgtype.Timestamptz
}

// ResourceUtilizationForApp will return resource utilization records for a given app.
func (q *Queries) ResourceUtilizationForApp(ctx context.Context, arg ResourceUtilizationForAppParams) ([]*ResourceUtilizationMetric, error) {
	rows, err := q.db.Query(ctx, resourceUtilizationForApp,
		arg.Env,
		arg.Team,
		arg.Name,
		arg.Kind,
		arg.ResourceType,
		arg.Start,
		arg.End,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ResourceUtilizationMetric
	for rows.Next() {
		var i ResourceUtilizationMetric
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Env,
			&i.Team,
			&i.Name,
			&i.Kind,
			&i.ResourceType,
			&i.Usage,
			&i.Request,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resourceUtilizationForTeam = `-- name: ResourceUtilizationForTeam :many
SELECT
    SUM(usage)::double precision AS usage,
    SUM(request)::double precision AS request,
    timestamp
FROM
    resource_utilization_metrics
WHERE
    env = $1
    AND team = $2
    AND resource_type = $3
    AND timestamp >= $4::timestamptz
    AND timestamp < $5::timestamptz
GROUP BY
    timestamp
ORDER BY
    timestamp ASC
`

type ResourceUtilizationForTeamParams struct {
	Env          string
	Team         string
	ResourceType ResourceType
	Start        pgtype.Timestamptz
	End          pgtype.Timestamptz
}

type ResourceUtilizationForTeamRow struct {
	Usage     float64
	Request   float64
	Timestamp pgtype.Timestamptz
}

// ResourceUtilizationForTeam will return resource utilization records for a given team.
func (q *Queries) ResourceUtilizationForTeam(ctx context.Context, arg ResourceUtilizationForTeamParams) ([]*ResourceUtilizationForTeamRow, error) {
	rows, err := q.db.Query(ctx, resourceUtilizationForTeam,
		arg.Env,
		arg.Team,
		arg.ResourceType,
		arg.Start,
		arg.End,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ResourceUtilizationForTeamRow
	for rows.Next() {
		var i ResourceUtilizationForTeamRow
		if err := rows.Scan(&i.Usage, &i.Request, &i.Timestamp); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resourceUtilizationOverageCostForTeam = `-- name: ResourceUtilizationOverageCostForTeam :many
SELECT
    SUM(usage)::double precision AS usage,
    SUM(request)::double precision AS request,
    env,
    name,
    kind,
    resource_type
FROM
    resource_utilization_metrics
WHERE
    team = $1
    AND timestamp >= $2::timestamptz
    AND timestamp < $3::timestamptz
GROUP BY
    env, name, kind, resource_type
HAVING
    SUM(request) > SUM(usage)
`

type ResourceUtilizationOverageCostForTeamParams struct {
	Team  string
	Start pgtype.Timestamptz
	End   pgtype.Timestamptz
}

type ResourceUtilizationOverageCostForTeamRow struct {
	Usage        float64
	Request      float64
	Env          string
	Name         string
	Kind         Kind
	ResourceType ResourceType
}

// ResourceUtilizationOverageCostForTeam will return overage records for a given team.
func (q *Queries) ResourceUtilizationOverageCostForTeam(ctx context.Context, arg ResourceUtilizationOverageCostForTeamParams) ([]*ResourceUtilizationOverageCostForTeamRow, error) {
	rows, err := q.db.Query(ctx, resourceUtilizationOverageCostForTeam, arg.Team, arg.Start, arg.End)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ResourceUtilizationOverageCostForTeamRow
	for rows.Next() {
		var i ResourceUtilizationOverageCostForTeamRow
		if err := rows.Scan(
			&i.Usage,
			&i.Request,
			&i.Env,
			&i.Name,
			&i.Kind,
			&i.ResourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
