apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
      labels:
        app: "{{ .Release.Name }}"
    spec:
      serviceAccountName: "{{ .Release.Name }}"
      containers:
        - name: "{{ .Chart.Name }}"
          env:
            - name: KUBERNETES_CLUSTERS
              value: "{{ .Values.kubernetes.clusters }}"
            - name: IAP_AUDIENCE
              value: "{{ .Values.audience }}"
            - name: TENANT
              value: "{{ .Values.tenant }}"
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}"
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1069
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Chart.Version }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
          {{- toYaml .Values.resources | nindent 12 }}