apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
      labels:
        app: "{{ .Release.Name }}"
    spec:
      serviceAccountName: "{{ .Release.Name }}"
      containers:
        - name: "{{ .Chart.Name }}"
          env:
            - name: KUBERNETES_CLUSTERS
              value: "{{ .Values.kubernetes.clusters }}"
            {{- if .Values.kubernetes.static }}
            - name: KUBERNETES_CLUSTERS_STATIC
              value: "{{ .Values.kubernetes.static }}"
            {{- end }}
            - name: IAP_AUDIENCE
              value: "{{ .Values.audience }}"
            - name: TENANT
              value: "{{ .Values.fasit.tenant.name }}"
            - name: FIELD_SELECTOR
              value: "{{ .Values.fieldSelector }}"
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}"
            {{- if eq .Tenant.Name "nav" }}
            - configMapRef:
                name: "{{ .Release.Name }}"-deprecated-ingresses
            {{- end }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1069
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Chart.Version }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "{{ .Values.resources.cpu }}"
              memory: "{{ .Values.resources.memory }}"
            requests:
              cpu: "{{ .Values.resources.cpu }}"
              memory: "{{ .Values.resources.memory }}"
