apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}"
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: teams-backend
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: hookd
  podSelector:
    matchLabels:
      app: "{{ .Release.Name }}"
  policyTypes:
    - Egress
