{{ if .Values.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: "{{ .Release.Name }}-alerts"
spec:
  groups:
    - name: "{{ .Release.Name }}-alerts"
      rules:
        - alert: Hookd requests failing
          expr: increase(errors_total{job="console-backend", component="hookd-client"}[1m]) > 0 
          for: 5m
          labels:
            namespace: nais-system
            severity: critical
            ping: nais-vakt
          annotations:
            consequence: Users may not be able to see deployments in console.
            action: "Check logs in console-backend and hookd"
        - alert: Teams requests failing
          expr: increase(errors_total{job="console-backend", component="teams-client"}[1m]) > 0 
          for: 5m
          labels:
            namespace: nais-system
            severity: critical
            ping: nais-vakt
          annotations:
            consequence: Users may not be able to see team info in console.
            action: "Check logs in console-backend and teams-backend"
        - alert: Kubernetes API server requests failing
          expr: increase(errors_total{job="console-backend", component="k8s-client"}[1m]) > 0 
          for: 5m
          labels:
            namespace: nais-system
            severity: critical
            ping: nais-vakt
          annotations:
            consequence: Users may not be able to see workload information in console.
            action: "Check logs in console-backend"
{{- end }}
