apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}"
type: Opaque
stringData:
  HOOKD_PSK: "{{ .Values.hookd.psk }}"
  TEAMS_TOKEN: "{{ .Values.teams.token }}"
  DEPENDENCYTRACK_PASSWORD: "{{ .Values.dependencytrack.password }}"
