environmentKinds:
  - management
dependencies:
  - allOf:
      - fqdn-policy
values:
  database.instance:
    displayName: Database instance
    computed:
      template: '"{{.Management.console_database_instance}}"'
  database.name:
    displayName: Database name
    computed:
      template: '"{{.Management.console_database_name}}"'
  database.user:
    displayName: Database user
    computed:
      template: '"{{.Management.console_database_user}}"'
  kubernetes.static:
    displayName: static cluster
    description: Comma-separated list of clusters with static credentials on the format 'name|apiserverHost|token'
    config:
      type: string
      secret: true
  kubernetes.clusters:
    displayName: clusters
    description: Comma-separated list of clusters to monitor
    required: true
    config:
      type: string
  audience:
    displayName: audience
    description: IAP audience
    required: true
    config:
      type: string
  fieldSelector:
    displayName: field selector
    description: Kubernetes field selector to filter out resources from api server
    config:
      type: string
  hookd.psk:
    description: The pre-shared key used to authenticate against hookd
    displayName: hookd pre-shared key
    computed:
      template: '"{{.Management.hookd_frontend_pre_shared_key}}"'
  host:
    computed:
      template: '{{ subdomain . "console" }}'
  resources.cpu:
    displayName: CPU
    description: CPU requirements (request == limit, because Autopilot)
    config:
      type: string
  resources.memory:
    displayName: Memory
    description: Memory requirements (request == limit, because Autopilot)
    config:
      type: string
  serviceaccount.email:
    displayName: sa email
    description: console-backend service account email
    computed:
      template: '"{{.Management.console_backend_serviceaccount_email}}"'
  teams.token:
    description: The pre-shared key used by console to authenticate against teams
    displayName: teams pre-shared key
    computed:
      template: '"{{.Management.console_teams_api_key}}"'
