image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images
  name: console-backend

host: ""

audience: ""

teams:
  token: ""

hookd:
  psk: ""

serviceaccount:
  email: ""

fasit:
  tenant:
    name: "dev-nais"

kubernetes:
  clusters: "dev,prod"
  static: ""

resources:
  cpu: 300m
  memory: 512Mi

alerts:
  enabled: true
