// Code generated by mockery. DO NOT EDIT.

package dependencytrack

import (
	context "context"

	client "github.com/nais/dependencytrack/pkg/client"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockInternalClient is an autogenerated mock type for the InternalClient type
type MockInternalClient struct {
	mock.Mock
}

type MockInternalClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalClient) EXPECT() *MockInternalClient_Expecter {
	return &MockInternalClient_Expecter{mock: &_m.Mock}
}

// AddToTeam provides a mock function with given fields: ctx, username, uuid
func (_m *MockInternalClient) AddToTeam(ctx context.Context, username string, uuid string) error {
	ret := _m.Called(ctx, username, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_AddToTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToTeam'
type MockInternalClient_AddToTeam_Call struct {
	*mock.Call
}

// AddToTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - uuid string
func (_e *MockInternalClient_Expecter) AddToTeam(ctx interface{}, username interface{}, uuid interface{}) *MockInternalClient_AddToTeam_Call {
	return &MockInternalClient_AddToTeam_Call{Call: _e.mock.On("AddToTeam", ctx, username, uuid)}
}

func (_c *MockInternalClient_AddToTeam_Call) Run(run func(ctx context.Context, username string, uuid string)) *MockInternalClient_AddToTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInternalClient_AddToTeam_Call) Return(_a0 error) *MockInternalClient_AddToTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_AddToTeam_Call) RunAndReturn(run func(context.Context, string, string) error) *MockInternalClient_AddToTeam_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeAdminPassword provides a mock function with given fields: ctx, oldPassword, newPassword
func (_m *MockInternalClient) ChangeAdminPassword(ctx context.Context, oldPassword string, newPassword string) error {
	ret := _m.Called(ctx, oldPassword, newPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_ChangeAdminPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeAdminPassword'
type MockInternalClient_ChangeAdminPassword_Call struct {
	*mock.Call
}

// ChangeAdminPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - oldPassword string
//   - newPassword string
func (_e *MockInternalClient_Expecter) ChangeAdminPassword(ctx interface{}, oldPassword interface{}, newPassword interface{}) *MockInternalClient_ChangeAdminPassword_Call {
	return &MockInternalClient_ChangeAdminPassword_Call{Call: _e.mock.On("ChangeAdminPassword", ctx, oldPassword, newPassword)}
}

func (_c *MockInternalClient_ChangeAdminPassword_Call) Run(run func(ctx context.Context, oldPassword string, newPassword string)) *MockInternalClient_ChangeAdminPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInternalClient_ChangeAdminPassword_Call) Return(_a0 error) *MockInternalClient_ChangeAdminPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_ChangeAdminPassword_Call) RunAndReturn(run func(context.Context, string, string) error) *MockInternalClient_ChangeAdminPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigPropertyAggregate provides a mock function with given fields: ctx, properties
func (_m *MockInternalClient) ConfigPropertyAggregate(ctx context.Context, properties []client.ConfigProperty) ([]client.ConfigProperty, error) {
	ret := _m.Called(ctx, properties)

	var r0 []client.ConfigProperty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []client.ConfigProperty) ([]client.ConfigProperty, error)); ok {
		return rf(ctx, properties)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []client.ConfigProperty) []client.ConfigProperty); ok {
		r0 = rf(ctx, properties)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ConfigProperty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []client.ConfigProperty) error); ok {
		r1 = rf(ctx, properties)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_ConfigPropertyAggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigPropertyAggregate'
type MockInternalClient_ConfigPropertyAggregate_Call struct {
	*mock.Call
}

// ConfigPropertyAggregate is a helper method to define mock.On call
//   - ctx context.Context
//   - properties []client.ConfigProperty
func (_e *MockInternalClient_Expecter) ConfigPropertyAggregate(ctx interface{}, properties interface{}) *MockInternalClient_ConfigPropertyAggregate_Call {
	return &MockInternalClient_ConfigPropertyAggregate_Call{Call: _e.mock.On("ConfigPropertyAggregate", ctx, properties)}
}

func (_c *MockInternalClient_ConfigPropertyAggregate_Call) Run(run func(ctx context.Context, properties []client.ConfigProperty)) *MockInternalClient_ConfigPropertyAggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]client.ConfigProperty))
	})
	return _c
}

func (_c *MockInternalClient_ConfigPropertyAggregate_Call) Return(_a0 []client.ConfigProperty, _a1 error) *MockInternalClient_ConfigPropertyAggregate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_ConfigPropertyAggregate_Call) RunAndReturn(run func(context.Context, []client.ConfigProperty) ([]client.ConfigProperty, error)) *MockInternalClient_ConfigPropertyAggregate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAdminUsers provides a mock function with given fields: ctx, users, teamUuid
func (_m *MockInternalClient) CreateAdminUsers(ctx context.Context, users *client.AdminUsers, teamUuid string) error {
	ret := _m.Called(ctx, users, teamUuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.AdminUsers, string) error); ok {
		r0 = rf(ctx, users, teamUuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_CreateAdminUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAdminUsers'
type MockInternalClient_CreateAdminUsers_Call struct {
	*mock.Call
}

// CreateAdminUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - users *client.AdminUsers
//   - teamUuid string
func (_e *MockInternalClient_Expecter) CreateAdminUsers(ctx interface{}, users interface{}, teamUuid interface{}) *MockInternalClient_CreateAdminUsers_Call {
	return &MockInternalClient_CreateAdminUsers_Call{Call: _e.mock.On("CreateAdminUsers", ctx, users, teamUuid)}
}

func (_c *MockInternalClient_CreateAdminUsers_Call) Run(run func(ctx context.Context, users *client.AdminUsers, teamUuid string)) *MockInternalClient_CreateAdminUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.AdminUsers), args[2].(string))
	})
	return _c
}

func (_c *MockInternalClient_CreateAdminUsers_Call) Return(_a0 error) *MockInternalClient_CreateAdminUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_CreateAdminUsers_Call) RunAndReturn(run func(context.Context, *client.AdminUsers, string) error) *MockInternalClient_CreateAdminUsers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChildProject provides a mock function with given fields: ctx, project, name, version, group, classifier, tags
func (_m *MockInternalClient) CreateChildProject(ctx context.Context, project *client.Project, name string, version string, group string, classifier string, tags []string) (*client.Project, error) {
	ret := _m.Called(ctx, project, name, version, group, classifier, tags)

	var r0 *client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.Project, string, string, string, string, []string) (*client.Project, error)); ok {
		return rf(ctx, project, name, version, group, classifier, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.Project, string, string, string, string, []string) *client.Project); ok {
		r0 = rf(ctx, project, name, version, group, classifier, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.Project, string, string, string, string, []string) error); ok {
		r1 = rf(ctx, project, name, version, group, classifier, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_CreateChildProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChildProject'
type MockInternalClient_CreateChildProject_Call struct {
	*mock.Call
}

// CreateChildProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project *client.Project
//   - name string
//   - version string
//   - group string
//   - classifier string
//   - tags []string
func (_e *MockInternalClient_Expecter) CreateChildProject(ctx interface{}, project interface{}, name interface{}, version interface{}, group interface{}, classifier interface{}, tags interface{}) *MockInternalClient_CreateChildProject_Call {
	return &MockInternalClient_CreateChildProject_Call{Call: _e.mock.On("CreateChildProject", ctx, project, name, version, group, classifier, tags)}
}

func (_c *MockInternalClient_CreateChildProject_Call) Run(run func(ctx context.Context, project *client.Project, name string, version string, group string, classifier string, tags []string)) *MockInternalClient_CreateChildProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.Project), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].([]string))
	})
	return _c
}

func (_c *MockInternalClient_CreateChildProject_Call) Return(_a0 *client.Project, _a1 error) *MockInternalClient_CreateChildProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_CreateChildProject_Call) RunAndReturn(run func(context.Context, *client.Project, string, string, string, string, []string) (*client.Project, error)) *MockInternalClient_CreateChildProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateManagedUser provides a mock function with given fields: ctx, username, password
func (_m *MockInternalClient) CreateManagedUser(ctx context.Context, username string, password string) error {
	ret := _m.Called(ctx, username, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_CreateManagedUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateManagedUser'
type MockInternalClient_CreateManagedUser_Call struct {
	*mock.Call
}

// CreateManagedUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockInternalClient_Expecter) CreateManagedUser(ctx interface{}, username interface{}, password interface{}) *MockInternalClient_CreateManagedUser_Call {
	return &MockInternalClient_CreateManagedUser_Call{Call: _e.mock.On("CreateManagedUser", ctx, username, password)}
}

func (_c *MockInternalClient_CreateManagedUser_Call) Run(run func(ctx context.Context, username string, password string)) *MockInternalClient_CreateManagedUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInternalClient_CreateManagedUser_Call) Return(_a0 error) *MockInternalClient_CreateManagedUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_CreateManagedUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockInternalClient_CreateManagedUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOidcUser provides a mock function with given fields: ctx, email
func (_m *MockInternalClient) CreateOidcUser(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_CreateOidcUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOidcUser'
type MockInternalClient_CreateOidcUser_Call struct {
	*mock.Call
}

// CreateOidcUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockInternalClient_Expecter) CreateOidcUser(ctx interface{}, email interface{}) *MockInternalClient_CreateOidcUser_Call {
	return &MockInternalClient_CreateOidcUser_Call{Call: _e.mock.On("CreateOidcUser", ctx, email)}
}

func (_c *MockInternalClient_CreateOidcUser_Call) Run(run func(ctx context.Context, email string)) *MockInternalClient_CreateOidcUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_CreateOidcUser_Call) Return(_a0 error) *MockInternalClient_CreateOidcUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_CreateOidcUser_Call) RunAndReturn(run func(context.Context, string) error) *MockInternalClient_CreateOidcUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function with given fields: ctx, name, version, group, tags
func (_m *MockInternalClient) CreateProject(ctx context.Context, name string, version string, group string, tags []string) (*client.Project, error) {
	ret := _m.Called(ctx, name, version, group, tags)

	var r0 *client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) (*client.Project, error)); ok {
		return rf(ctx, name, version, group, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) *client.Project); ok {
		r0 = rf(ctx, name, version, group, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []string) error); ok {
		r1 = rf(ctx, name, version, group, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockInternalClient_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version string
//   - group string
//   - tags []string
func (_e *MockInternalClient_Expecter) CreateProject(ctx interface{}, name interface{}, version interface{}, group interface{}, tags interface{}) *MockInternalClient_CreateProject_Call {
	return &MockInternalClient_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, name, version, group, tags)}
}

func (_c *MockInternalClient_CreateProject_Call) Run(run func(ctx context.Context, name string, version string, group string, tags []string)) *MockInternalClient_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *MockInternalClient_CreateProject_Call) Return(_a0 *client.Project, _a1 error) *MockInternalClient_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_CreateProject_Call) RunAndReturn(run func(context.Context, string, string, string, []string) (*client.Project, error)) *MockInternalClient_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: ctx, teamName, permissions
func (_m *MockInternalClient) CreateTeam(ctx context.Context, teamName string, permissions []client.Permission) (*client.Team, error) {
	ret := _m.Called(ctx, teamName, permissions)

	var r0 *client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []client.Permission) (*client.Team, error)); ok {
		return rf(ctx, teamName, permissions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []client.Permission) *client.Team); ok {
		r0 = rf(ctx, teamName, permissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []client.Permission) error); ok {
		r1 = rf(ctx, teamName, permissions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockInternalClient_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - permissions []client.Permission
func (_e *MockInternalClient_Expecter) CreateTeam(ctx interface{}, teamName interface{}, permissions interface{}) *MockInternalClient_CreateTeam_Call {
	return &MockInternalClient_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, teamName, permissions)}
}

func (_c *MockInternalClient_CreateTeam_Call) Run(run func(ctx context.Context, teamName string, permissions []client.Permission)) *MockInternalClient_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]client.Permission))
	})
	return _c
}

func (_c *MockInternalClient_CreateTeam_Call) Return(_a0 *client.Team, _a1 error) *MockInternalClient_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_CreateTeam_Call) RunAndReturn(run func(context.Context, string, []client.Permission) (*client.Team, error)) *MockInternalClient_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteManagedUser provides a mock function with given fields: ctx, username
func (_m *MockInternalClient) DeleteManagedUser(ctx context.Context, username string) error {
	ret := _m.Called(ctx, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_DeleteManagedUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManagedUser'
type MockInternalClient_DeleteManagedUser_Call struct {
	*mock.Call
}

// DeleteManagedUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockInternalClient_Expecter) DeleteManagedUser(ctx interface{}, username interface{}) *MockInternalClient_DeleteManagedUser_Call {
	return &MockInternalClient_DeleteManagedUser_Call{Call: _e.mock.On("DeleteManagedUser", ctx, username)}
}

func (_c *MockInternalClient_DeleteManagedUser_Call) Run(run func(ctx context.Context, username string)) *MockInternalClient_DeleteManagedUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_DeleteManagedUser_Call) Return(_a0 error) *MockInternalClient_DeleteManagedUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_DeleteManagedUser_Call) RunAndReturn(run func(context.Context, string) error) *MockInternalClient_DeleteManagedUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOidcUser provides a mock function with given fields: ctx, username
func (_m *MockInternalClient) DeleteOidcUser(ctx context.Context, username string) error {
	ret := _m.Called(ctx, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_DeleteOidcUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOidcUser'
type MockInternalClient_DeleteOidcUser_Call struct {
	*mock.Call
}

// DeleteOidcUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockInternalClient_Expecter) DeleteOidcUser(ctx interface{}, username interface{}) *MockInternalClient_DeleteOidcUser_Call {
	return &MockInternalClient_DeleteOidcUser_Call{Call: _e.mock.On("DeleteOidcUser", ctx, username)}
}

func (_c *MockInternalClient_DeleteOidcUser_Call) Run(run func(ctx context.Context, username string)) *MockInternalClient_DeleteOidcUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_DeleteOidcUser_Call) Return(_a0 error) *MockInternalClient_DeleteOidcUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_DeleteOidcUser_Call) RunAndReturn(run func(context.Context, string) error) *MockInternalClient_DeleteOidcUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function with given fields: ctx, uuid
func (_m *MockInternalClient) DeleteProject(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockInternalClient_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockInternalClient_Expecter) DeleteProject(ctx interface{}, uuid interface{}) *MockInternalClient_DeleteProject_Call {
	return &MockInternalClient_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, uuid)}
}

func (_c *MockInternalClient_DeleteProject_Call) Run(run func(ctx context.Context, uuid string)) *MockInternalClient_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_DeleteProject_Call) Return(_a0 error) *MockInternalClient_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_DeleteProject_Call) RunAndReturn(run func(context.Context, string) error) *MockInternalClient_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProjects provides a mock function with given fields: ctx, name
func (_m *MockInternalClient) DeleteProjects(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_DeleteProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProjects'
type MockInternalClient_DeleteProjects_Call struct {
	*mock.Call
}

// DeleteProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockInternalClient_Expecter) DeleteProjects(ctx interface{}, name interface{}) *MockInternalClient_DeleteProjects_Call {
	return &MockInternalClient_DeleteProjects_Call{Call: _e.mock.On("DeleteProjects", ctx, name)}
}

func (_c *MockInternalClient_DeleteProjects_Call) Run(run func(ctx context.Context, name string)) *MockInternalClient_DeleteProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_DeleteProjects_Call) Return(_a0 error) *MockInternalClient_DeleteProjects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_DeleteProjects_Call) RunAndReturn(run func(context.Context, string) error) *MockInternalClient_DeleteProjects_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeam provides a mock function with given fields: ctx, uuid
func (_m *MockInternalClient) DeleteTeam(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type MockInternalClient_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockInternalClient_Expecter) DeleteTeam(ctx interface{}, uuid interface{}) *MockInternalClient_DeleteTeam_Call {
	return &MockInternalClient_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", ctx, uuid)}
}

func (_c *MockInternalClient_DeleteTeam_Call) Run(run func(ctx context.Context, uuid string)) *MockInternalClient_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_DeleteTeam_Call) Return(_a0 error) *MockInternalClient_DeleteTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_DeleteTeam_Call) RunAndReturn(run func(context.Context, string) error) *MockInternalClient_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserMembership provides a mock function with given fields: ctx, uuid, username
func (_m *MockInternalClient) DeleteUserMembership(ctx context.Context, uuid string, username string) error {
	ret := _m.Called(ctx, uuid, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, uuid, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_DeleteUserMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserMembership'
type MockInternalClient_DeleteUserMembership_Call struct {
	*mock.Call
}

// DeleteUserMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - username string
func (_e *MockInternalClient_Expecter) DeleteUserMembership(ctx interface{}, uuid interface{}, username interface{}) *MockInternalClient_DeleteUserMembership_Call {
	return &MockInternalClient_DeleteUserMembership_Call{Call: _e.mock.On("DeleteUserMembership", ctx, uuid, username)}
}

func (_c *MockInternalClient_DeleteUserMembership_Call) Run(run func(ctx context.Context, uuid string, username string)) *MockInternalClient_DeleteUserMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInternalClient_DeleteUserMembership_Call) Return(_a0 error) *MockInternalClient_DeleteUserMembership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_DeleteUserMembership_Call) RunAndReturn(run func(context.Context, string, string) error) *MockInternalClient_DeleteUserMembership_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateApiKey provides a mock function with given fields: ctx, uuid
func (_m *MockInternalClient) GenerateApiKey(ctx context.Context, uuid string) (string, error) {
	ret := _m.Called(ctx, uuid)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GenerateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateApiKey'
type MockInternalClient_GenerateApiKey_Call struct {
	*mock.Call
}

// GenerateApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockInternalClient_Expecter) GenerateApiKey(ctx interface{}, uuid interface{}) *MockInternalClient_GenerateApiKey_Call {
	return &MockInternalClient_GenerateApiKey_Call{Call: _e.mock.On("GenerateApiKey", ctx, uuid)}
}

func (_c *MockInternalClient_GenerateApiKey_Call) Run(run func(ctx context.Context, uuid string)) *MockInternalClient_GenerateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_GenerateApiKey_Call) Return(_a0 string, _a1 error) *MockInternalClient_GenerateApiKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GenerateApiKey_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockInternalClient_GenerateApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigProperties provides a mock function with given fields: ctx
func (_m *MockInternalClient) GetConfigProperties(ctx context.Context) ([]client.ConfigProperty, error) {
	ret := _m.Called(ctx)

	var r0 []client.ConfigProperty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.ConfigProperty, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.ConfigProperty); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ConfigProperty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GetConfigProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigProperties'
type MockInternalClient_GetConfigProperties_Call struct {
	*mock.Call
}

// GetConfigProperties is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInternalClient_Expecter) GetConfigProperties(ctx interface{}) *MockInternalClient_GetConfigProperties_Call {
	return &MockInternalClient_GetConfigProperties_Call{Call: _e.mock.On("GetConfigProperties", ctx)}
}

func (_c *MockInternalClient_GetConfigProperties_Call) Run(run func(ctx context.Context)) *MockInternalClient_GetConfigProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInternalClient_GetConfigProperties_Call) Return(_a0 []client.ConfigProperty, _a1 error) *MockInternalClient_GetConfigProperties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GetConfigProperties_Call) RunAndReturn(run func(context.Context) ([]client.ConfigProperty, error)) *MockInternalClient_GetConfigProperties_Call {
	_c.Call.Return(run)
	return _c
}

// GetEcosystems provides a mock function with given fields: ctx
func (_m *MockInternalClient) GetEcosystems(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GetEcosystems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEcosystems'
type MockInternalClient_GetEcosystems_Call struct {
	*mock.Call
}

// GetEcosystems is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInternalClient_Expecter) GetEcosystems(ctx interface{}) *MockInternalClient_GetEcosystems_Call {
	return &MockInternalClient_GetEcosystems_Call{Call: _e.mock.On("GetEcosystems", ctx)}
}

func (_c *MockInternalClient_GetEcosystems_Call) Run(run func(ctx context.Context)) *MockInternalClient_GetEcosystems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInternalClient_GetEcosystems_Call) Return(_a0 []string, _a1 error) *MockInternalClient_GetEcosystems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GetEcosystems_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockInternalClient_GetEcosystems_Call {
	_c.Call.Return(run)
	return _c
}

// GetFindings provides a mock function with given fields: ctx, projectUuid
func (_m *MockInternalClient) GetFindings(ctx context.Context, projectUuid string) ([]*client.Finding, error) {
	ret := _m.Called(ctx, projectUuid)

	var r0 []*client.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*client.Finding, error)); ok {
		return rf(ctx, projectUuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*client.Finding); ok {
		r0 = rf(ctx, projectUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GetFindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFindings'
type MockInternalClient_GetFindings_Call struct {
	*mock.Call
}

// GetFindings is a helper method to define mock.On call
//   - ctx context.Context
//   - projectUuid string
func (_e *MockInternalClient_Expecter) GetFindings(ctx interface{}, projectUuid interface{}) *MockInternalClient_GetFindings_Call {
	return &MockInternalClient_GetFindings_Call{Call: _e.mock.On("GetFindings", ctx, projectUuid)}
}

func (_c *MockInternalClient_GetFindings_Call) Run(run func(ctx context.Context, projectUuid string)) *MockInternalClient_GetFindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_GetFindings_Call) Return(_a0 []*client.Finding, _a1 error) *MockInternalClient_GetFindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GetFindings_Call) RunAndReturn(run func(context.Context, string) ([]*client.Finding, error)) *MockInternalClient_GetFindings_Call {
	_c.Call.Return(run)
	return _c
}

// GetOidcUsers provides a mock function with given fields: ctx
func (_m *MockInternalClient) GetOidcUsers(ctx context.Context) ([]client.User, error) {
	ret := _m.Called(ctx)

	var r0 []client.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GetOidcUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOidcUsers'
type MockInternalClient_GetOidcUsers_Call struct {
	*mock.Call
}

// GetOidcUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInternalClient_Expecter) GetOidcUsers(ctx interface{}) *MockInternalClient_GetOidcUsers_Call {
	return &MockInternalClient_GetOidcUsers_Call{Call: _e.mock.On("GetOidcUsers", ctx)}
}

func (_c *MockInternalClient_GetOidcUsers_Call) Run(run func(ctx context.Context)) *MockInternalClient_GetOidcUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInternalClient_GetOidcUsers_Call) Return(_a0 []client.User, _a1 error) *MockInternalClient_GetOidcUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GetOidcUsers_Call) RunAndReturn(run func(context.Context) ([]client.User, error)) *MockInternalClient_GetOidcUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: ctx, name, version
func (_m *MockInternalClient) GetProject(ctx context.Context, name string, version string) (*client.Project, error) {
	ret := _m.Called(ctx, name, version)

	var r0 *client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.Project, error)); ok {
		return rf(ctx, name, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.Project); ok {
		r0 = rf(ctx, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockInternalClient_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version string
func (_e *MockInternalClient_Expecter) GetProject(ctx interface{}, name interface{}, version interface{}) *MockInternalClient_GetProject_Call {
	return &MockInternalClient_GetProject_Call{Call: _e.mock.On("GetProject", ctx, name, version)}
}

func (_c *MockInternalClient_GetProject_Call) Run(run func(ctx context.Context, name string, version string)) *MockInternalClient_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInternalClient_GetProject_Call) Return(_a0 *client.Project, _a1 error) *MockInternalClient_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GetProject_Call) RunAndReturn(run func(context.Context, string, string) (*client.Project, error)) *MockInternalClient_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjects provides a mock function with given fields: ctx
func (_m *MockInternalClient) GetProjects(ctx context.Context) ([]*client.Project, error) {
	ret := _m.Called(ctx)

	var r0 []*client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*client.Project, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*client.Project); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GetProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjects'
type MockInternalClient_GetProjects_Call struct {
	*mock.Call
}

// GetProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInternalClient_Expecter) GetProjects(ctx interface{}) *MockInternalClient_GetProjects_Call {
	return &MockInternalClient_GetProjects_Call{Call: _e.mock.On("GetProjects", ctx)}
}

func (_c *MockInternalClient_GetProjects_Call) Run(run func(ctx context.Context)) *MockInternalClient_GetProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInternalClient_GetProjects_Call) Return(_a0 []*client.Project, _a1 error) *MockInternalClient_GetProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GetProjects_Call) RunAndReturn(run func(context.Context) ([]*client.Project, error)) *MockInternalClient_GetProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectsByTag provides a mock function with given fields: ctx, tag
func (_m *MockInternalClient) GetProjectsByTag(ctx context.Context, tag string) ([]*client.Project, error) {
	ret := _m.Called(ctx, tag)

	var r0 []*client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*client.Project, error)); ok {
		return rf(ctx, tag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*client.Project); ok {
		r0 = rf(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GetProjectsByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectsByTag'
type MockInternalClient_GetProjectsByTag_Call struct {
	*mock.Call
}

// GetProjectsByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
func (_e *MockInternalClient_Expecter) GetProjectsByTag(ctx interface{}, tag interface{}) *MockInternalClient_GetProjectsByTag_Call {
	return &MockInternalClient_GetProjectsByTag_Call{Call: _e.mock.On("GetProjectsByTag", ctx, tag)}
}

func (_c *MockInternalClient_GetProjectsByTag_Call) Run(run func(ctx context.Context, tag string)) *MockInternalClient_GetProjectsByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_GetProjectsByTag_Call) Return(_a0 []*client.Project, _a1 error) *MockInternalClient_GetProjectsByTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GetProjectsByTag_Call) RunAndReturn(run func(context.Context, string) ([]*client.Project, error)) *MockInternalClient_GetProjectsByTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, team
func (_m *MockInternalClient) GetTeam(ctx context.Context, team string) (*client.Team, error) {
	ret := _m.Called(ctx, team)

	var r0 *client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Team, error)); ok {
		return rf(ctx, team)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Team); ok {
		r0 = rf(ctx, team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockInternalClient_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team string
func (_e *MockInternalClient_Expecter) GetTeam(ctx interface{}, team interface{}) *MockInternalClient_GetTeam_Call {
	return &MockInternalClient_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, team)}
}

func (_c *MockInternalClient_GetTeam_Call) Run(run func(ctx context.Context, team string)) *MockInternalClient_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_GetTeam_Call) Return(_a0 *client.Team, _a1 error) *MockInternalClient_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*client.Team, error)) *MockInternalClient_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeams provides a mock function with given fields: ctx
func (_m *MockInternalClient) GetTeams(ctx context.Context) ([]client.Team, error) {
	ret := _m.Called(ctx)

	var r0 []client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_GetTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeams'
type MockInternalClient_GetTeams_Call struct {
	*mock.Call
}

// GetTeams is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInternalClient_Expecter) GetTeams(ctx interface{}) *MockInternalClient_GetTeams_Call {
	return &MockInternalClient_GetTeams_Call{Call: _e.mock.On("GetTeams", ctx)}
}

func (_c *MockInternalClient_GetTeams_Call) Run(run func(ctx context.Context)) *MockInternalClient_GetTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInternalClient_GetTeams_Call) Return(_a0 []client.Team, _a1 error) *MockInternalClient_GetTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_GetTeams_Call) RunAndReturn(run func(context.Context) ([]client.Team, error)) *MockInternalClient_GetTeams_Call {
	_c.Call.Return(run)
	return _c
}

// Headers provides a mock function with given fields: ctx
func (_m *MockInternalClient) Headers(ctx context.Context) (http.Header, error) {
	ret := _m.Called(ctx)

	var r0 http.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (http.Header, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) http.Header); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_Headers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Headers'
type MockInternalClient_Headers_Call struct {
	*mock.Call
}

// Headers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInternalClient_Expecter) Headers(ctx interface{}) *MockInternalClient_Headers_Call {
	return &MockInternalClient_Headers_Call{Call: _e.mock.On("Headers", ctx)}
}

func (_c *MockInternalClient_Headers_Call) Run(run func(ctx context.Context)) *MockInternalClient_Headers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInternalClient_Headers_Call) Return(_a0 http.Header, _a1 error) *MockInternalClient_Headers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_Headers_Call) RunAndReturn(run func(context.Context) (http.Header, error)) *MockInternalClient_Headers_Call {
	_c.Call.Return(run)
	return _c
}

// PortfolioRefresh provides a mock function with given fields: ctx
func (_m *MockInternalClient) PortfolioRefresh(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_PortfolioRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PortfolioRefresh'
type MockInternalClient_PortfolioRefresh_Call struct {
	*mock.Call
}

// PortfolioRefresh is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInternalClient_Expecter) PortfolioRefresh(ctx interface{}) *MockInternalClient_PortfolioRefresh_Call {
	return &MockInternalClient_PortfolioRefresh_Call{Call: _e.mock.On("PortfolioRefresh", ctx)}
}

func (_c *MockInternalClient_PortfolioRefresh_Call) Run(run func(ctx context.Context)) *MockInternalClient_PortfolioRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInternalClient_PortfolioRefresh_Call) Return(_a0 error) *MockInternalClient_PortfolioRefresh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_PortfolioRefresh_Call) RunAndReturn(run func(context.Context) error) *MockInternalClient_PortfolioRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAdminUsers provides a mock function with given fields: ctx, users
func (_m *MockInternalClient) RemoveAdminUsers(ctx context.Context, users *client.AdminUsers) error {
	ret := _m.Called(ctx, users)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.AdminUsers) error); ok {
		r0 = rf(ctx, users)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_RemoveAdminUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAdminUsers'
type MockInternalClient_RemoveAdminUsers_Call struct {
	*mock.Call
}

// RemoveAdminUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - users *client.AdminUsers
func (_e *MockInternalClient_Expecter) RemoveAdminUsers(ctx interface{}, users interface{}) *MockInternalClient_RemoveAdminUsers_Call {
	return &MockInternalClient_RemoveAdminUsers_Call{Call: _e.mock.On("RemoveAdminUsers", ctx, users)}
}

func (_c *MockInternalClient_RemoveAdminUsers_Call) Run(run func(ctx context.Context, users *client.AdminUsers)) *MockInternalClient_RemoveAdminUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.AdminUsers))
	})
	return _c
}

func (_c *MockInternalClient_RemoveAdminUsers_Call) Return(_a0 error) *MockInternalClient_RemoveAdminUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_RemoveAdminUsers_Call) RunAndReturn(run func(context.Context, *client.AdminUsers) error) *MockInternalClient_RemoveAdminUsers_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerAnalysis provides a mock function with given fields: ctx, projectUuid
func (_m *MockInternalClient) TriggerAnalysis(ctx context.Context, projectUuid string) error {
	ret := _m.Called(ctx, projectUuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, projectUuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_TriggerAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerAnalysis'
type MockInternalClient_TriggerAnalysis_Call struct {
	*mock.Call
}

// TriggerAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - projectUuid string
func (_e *MockInternalClient_Expecter) TriggerAnalysis(ctx interface{}, projectUuid interface{}) *MockInternalClient_TriggerAnalysis_Call {
	return &MockInternalClient_TriggerAnalysis_Call{Call: _e.mock.On("TriggerAnalysis", ctx, projectUuid)}
}

func (_c *MockInternalClient_TriggerAnalysis_Call) Run(run func(ctx context.Context, projectUuid string)) *MockInternalClient_TriggerAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInternalClient_TriggerAnalysis_Call) Return(_a0 error) *MockInternalClient_TriggerAnalysis_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_TriggerAnalysis_Call) RunAndReturn(run func(context.Context, string) error) *MockInternalClient_TriggerAnalysis_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: ctx, uuid, name, version, group, tags
func (_m *MockInternalClient) UpdateProject(ctx context.Context, uuid string, name string, version string, group string, tags []string) (*client.Project, error) {
	ret := _m.Called(ctx, uuid, name, version, group, tags)

	var r0 *client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, []string) (*client.Project, error)); ok {
		return rf(ctx, uuid, name, version, group, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, []string) *client.Project); ok {
		r0 = rf(ctx, uuid, name, version, group, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, []string) error); ok {
		r1 = rf(ctx, uuid, name, version, group, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockInternalClient_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - name string
//   - version string
//   - group string
//   - tags []string
func (_e *MockInternalClient_Expecter) UpdateProject(ctx interface{}, uuid interface{}, name interface{}, version interface{}, group interface{}, tags interface{}) *MockInternalClient_UpdateProject_Call {
	return &MockInternalClient_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, uuid, name, version, group, tags)}
}

func (_c *MockInternalClient_UpdateProject_Call) Run(run func(ctx context.Context, uuid string, name string, version string, group string, tags []string)) *MockInternalClient_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].([]string))
	})
	return _c
}

func (_c *MockInternalClient_UpdateProject_Call) Return(_a0 *client.Project, _a1 error) *MockInternalClient_UpdateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_UpdateProject_Call) RunAndReturn(run func(context.Context, string, string, string, string, []string) (*client.Project, error)) *MockInternalClient_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProjectInfo provides a mock function with given fields: ctx, uuid, version, group, tags
func (_m *MockInternalClient) UpdateProjectInfo(ctx context.Context, uuid string, version string, group string, tags []string) error {
	ret := _m.Called(ctx, uuid, version, group, tags)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) error); ok {
		r0 = rf(ctx, uuid, version, group, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_UpdateProjectInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProjectInfo'
type MockInternalClient_UpdateProjectInfo_Call struct {
	*mock.Call
}

// UpdateProjectInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - version string
//   - group string
//   - tags []string
func (_e *MockInternalClient_Expecter) UpdateProjectInfo(ctx interface{}, uuid interface{}, version interface{}, group interface{}, tags interface{}) *MockInternalClient_UpdateProjectInfo_Call {
	return &MockInternalClient_UpdateProjectInfo_Call{Call: _e.mock.On("UpdateProjectInfo", ctx, uuid, version, group, tags)}
}

func (_c *MockInternalClient_UpdateProjectInfo_Call) Run(run func(ctx context.Context, uuid string, version string, group string, tags []string)) *MockInternalClient_UpdateProjectInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *MockInternalClient_UpdateProjectInfo_Call) Return(_a0 error) *MockInternalClient_UpdateProjectInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_UpdateProjectInfo_Call) RunAndReturn(run func(context.Context, string, string, string, []string) error) *MockInternalClient_UpdateProjectInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UploadProject provides a mock function with given fields: ctx, name, version, parentUuid, autoCreate, bom
func (_m *MockInternalClient) UploadProject(ctx context.Context, name string, version string, parentUuid string, autoCreate bool, bom []byte) error {
	ret := _m.Called(ctx, name, version, parentUuid, autoCreate, bom)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool, []byte) error); ok {
		r0 = rf(ctx, name, version, parentUuid, autoCreate, bom)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInternalClient_UploadProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadProject'
type MockInternalClient_UploadProject_Call struct {
	*mock.Call
}

// UploadProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version string
//   - parentUuid string
//   - autoCreate bool
//   - bom []byte
func (_e *MockInternalClient_Expecter) UploadProject(ctx interface{}, name interface{}, version interface{}, parentUuid interface{}, autoCreate interface{}, bom interface{}) *MockInternalClient_UploadProject_Call {
	return &MockInternalClient_UploadProject_Call{Call: _e.mock.On("UploadProject", ctx, name, version, parentUuid, autoCreate, bom)}
}

func (_c *MockInternalClient_UploadProject_Call) Run(run func(ctx context.Context, name string, version string, parentUuid string, autoCreate bool, bom []byte)) *MockInternalClient_UploadProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool), args[5].([]byte))
	})
	return _c
}

func (_c *MockInternalClient_UploadProject_Call) Return(_a0 error) *MockInternalClient_UploadProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInternalClient_UploadProject_Call) RunAndReturn(run func(context.Context, string, string, string, bool, []byte) error) *MockInternalClient_UploadProject_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with given fields: ctx
func (_m *MockInternalClient) Version(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInternalClient_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockInternalClient_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInternalClient_Expecter) Version(ctx interface{}) *MockInternalClient_Version_Call {
	return &MockInternalClient_Version_Call{Call: _e.mock.On("Version", ctx)}
}

func (_c *MockInternalClient_Version_Call) Run(run func(ctx context.Context)) *MockInternalClient_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInternalClient_Version_Call) Return(_a0 string, _a1 error) *MockInternalClient_Version_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInternalClient_Version_Call) RunAndReturn(run func(context.Context) (string, error)) *MockInternalClient_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInternalClient creates a new instance of MockInternalClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalClient(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockInternalClient {
	mock := &MockInternalClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
