// Code generated by mockery. DO NOT EDIT.

package dtrack

import (
	context "context"

	client "github.com/nais/dependencytrack/pkg/client"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockDependencytrackClient is an autogenerated mock type for the DependencytrackClient type
type MockDependencytrackClient struct {
	mock.Mock
}

type MockDependencytrackClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDependencytrackClient) EXPECT() *MockDependencytrackClient_Expecter {
	return &MockDependencytrackClient_Expecter{mock: &_m.Mock}
}

// AddToTeam provides a mock function with given fields: ctx, username, uuid
func (_m *MockDependencytrackClient) AddToTeam(ctx context.Context, username string, uuid string) error {
	ret := _m.Called(ctx, username, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_AddToTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToTeam'
type MockDependencytrackClient_AddToTeam_Call struct {
	*mock.Call
}

// AddToTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - uuid string
func (_e *MockDependencytrackClient_Expecter) AddToTeam(ctx interface{}, username interface{}, uuid interface{}) *MockDependencytrackClient_AddToTeam_Call {
	return &MockDependencytrackClient_AddToTeam_Call{Call: _e.mock.On("AddToTeam", ctx, username, uuid)}
}

func (_c *MockDependencytrackClient_AddToTeam_Call) Run(run func(ctx context.Context, username string, uuid string)) *MockDependencytrackClient_AddToTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_AddToTeam_Call) Return(_a0 error) *MockDependencytrackClient_AddToTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_AddToTeam_Call) RunAndReturn(run func(context.Context, string, string) error) *MockDependencytrackClient_AddToTeam_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeAdminPassword provides a mock function with given fields: ctx, oldPassword, newPassword
func (_m *MockDependencytrackClient) ChangeAdminPassword(ctx context.Context, oldPassword string, newPassword string) error {
	ret := _m.Called(ctx, oldPassword, newPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_ChangeAdminPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeAdminPassword'
type MockDependencytrackClient_ChangeAdminPassword_Call struct {
	*mock.Call
}

// ChangeAdminPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - oldPassword string
//   - newPassword string
func (_e *MockDependencytrackClient_Expecter) ChangeAdminPassword(ctx interface{}, oldPassword interface{}, newPassword interface{}) *MockDependencytrackClient_ChangeAdminPassword_Call {
	return &MockDependencytrackClient_ChangeAdminPassword_Call{Call: _e.mock.On("ChangeAdminPassword", ctx, oldPassword, newPassword)}
}

func (_c *MockDependencytrackClient_ChangeAdminPassword_Call) Run(run func(ctx context.Context, oldPassword string, newPassword string)) *MockDependencytrackClient_ChangeAdminPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_ChangeAdminPassword_Call) Return(_a0 error) *MockDependencytrackClient_ChangeAdminPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_ChangeAdminPassword_Call) RunAndReturn(run func(context.Context, string, string) error) *MockDependencytrackClient_ChangeAdminPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigPropertyAggregate provides a mock function with given fields: ctx, properties
func (_m *MockDependencytrackClient) ConfigPropertyAggregate(ctx context.Context, properties []client.ConfigProperty) ([]client.ConfigProperty, error) {
	ret := _m.Called(ctx, properties)

	var r0 []client.ConfigProperty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []client.ConfigProperty) ([]client.ConfigProperty, error)); ok {
		return rf(ctx, properties)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []client.ConfigProperty) []client.ConfigProperty); ok {
		r0 = rf(ctx, properties)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ConfigProperty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []client.ConfigProperty) error); ok {
		r1 = rf(ctx, properties)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_ConfigPropertyAggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigPropertyAggregate'
type MockDependencytrackClient_ConfigPropertyAggregate_Call struct {
	*mock.Call
}

// ConfigPropertyAggregate is a helper method to define mock.On call
//   - ctx context.Context
//   - properties []client.ConfigProperty
func (_e *MockDependencytrackClient_Expecter) ConfigPropertyAggregate(ctx interface{}, properties interface{}) *MockDependencytrackClient_ConfigPropertyAggregate_Call {
	return &MockDependencytrackClient_ConfigPropertyAggregate_Call{Call: _e.mock.On("ConfigPropertyAggregate", ctx, properties)}
}

func (_c *MockDependencytrackClient_ConfigPropertyAggregate_Call) Run(run func(ctx context.Context, properties []client.ConfigProperty)) *MockDependencytrackClient_ConfigPropertyAggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]client.ConfigProperty))
	})
	return _c
}

func (_c *MockDependencytrackClient_ConfigPropertyAggregate_Call) Return(_a0 []client.ConfigProperty, _a1 error) *MockDependencytrackClient_ConfigPropertyAggregate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_ConfigPropertyAggregate_Call) RunAndReturn(run func(context.Context, []client.ConfigProperty) ([]client.ConfigProperty, error)) *MockDependencytrackClient_ConfigPropertyAggregate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAdminUsers provides a mock function with given fields: ctx, users, teamUuid
func (_m *MockDependencytrackClient) CreateAdminUsers(ctx context.Context, users *client.AdminUsers, teamUuid string) error {
	ret := _m.Called(ctx, users, teamUuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.AdminUsers, string) error); ok {
		r0 = rf(ctx, users, teamUuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_CreateAdminUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAdminUsers'
type MockDependencytrackClient_CreateAdminUsers_Call struct {
	*mock.Call
}

// CreateAdminUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - users *client.AdminUsers
//   - teamUuid string
func (_e *MockDependencytrackClient_Expecter) CreateAdminUsers(ctx interface{}, users interface{}, teamUuid interface{}) *MockDependencytrackClient_CreateAdminUsers_Call {
	return &MockDependencytrackClient_CreateAdminUsers_Call{Call: _e.mock.On("CreateAdminUsers", ctx, users, teamUuid)}
}

func (_c *MockDependencytrackClient_CreateAdminUsers_Call) Run(run func(ctx context.Context, users *client.AdminUsers, teamUuid string)) *MockDependencytrackClient_CreateAdminUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.AdminUsers), args[2].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_CreateAdminUsers_Call) Return(_a0 error) *MockDependencytrackClient_CreateAdminUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_CreateAdminUsers_Call) RunAndReturn(run func(context.Context, *client.AdminUsers, string) error) *MockDependencytrackClient_CreateAdminUsers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChildProject provides a mock function with given fields: ctx, project, name, version, group, classifier, tags
func (_m *MockDependencytrackClient) CreateChildProject(ctx context.Context, project *client.Project, name string, version string, group string, classifier string, tags []string) (*client.Project, error) {
	ret := _m.Called(ctx, project, name, version, group, classifier, tags)

	var r0 *client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.Project, string, string, string, string, []string) (*client.Project, error)); ok {
		return rf(ctx, project, name, version, group, classifier, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.Project, string, string, string, string, []string) *client.Project); ok {
		r0 = rf(ctx, project, name, version, group, classifier, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.Project, string, string, string, string, []string) error); ok {
		r1 = rf(ctx, project, name, version, group, classifier, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_CreateChildProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChildProject'
type MockDependencytrackClient_CreateChildProject_Call struct {
	*mock.Call
}

// CreateChildProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project *client.Project
//   - name string
//   - version string
//   - group string
//   - classifier string
//   - tags []string
func (_e *MockDependencytrackClient_Expecter) CreateChildProject(ctx interface{}, project interface{}, name interface{}, version interface{}, group interface{}, classifier interface{}, tags interface{}) *MockDependencytrackClient_CreateChildProject_Call {
	return &MockDependencytrackClient_CreateChildProject_Call{Call: _e.mock.On("CreateChildProject", ctx, project, name, version, group, classifier, tags)}
}

func (_c *MockDependencytrackClient_CreateChildProject_Call) Run(run func(ctx context.Context, project *client.Project, name string, version string, group string, classifier string, tags []string)) *MockDependencytrackClient_CreateChildProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.Project), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].([]string))
	})
	return _c
}

func (_c *MockDependencytrackClient_CreateChildProject_Call) Return(_a0 *client.Project, _a1 error) *MockDependencytrackClient_CreateChildProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_CreateChildProject_Call) RunAndReturn(run func(context.Context, *client.Project, string, string, string, string, []string) (*client.Project, error)) *MockDependencytrackClient_CreateChildProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateManagedUser provides a mock function with given fields: ctx, username, password
func (_m *MockDependencytrackClient) CreateManagedUser(ctx context.Context, username string, password string) error {
	ret := _m.Called(ctx, username, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_CreateManagedUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateManagedUser'
type MockDependencytrackClient_CreateManagedUser_Call struct {
	*mock.Call
}

// CreateManagedUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockDependencytrackClient_Expecter) CreateManagedUser(ctx interface{}, username interface{}, password interface{}) *MockDependencytrackClient_CreateManagedUser_Call {
	return &MockDependencytrackClient_CreateManagedUser_Call{Call: _e.mock.On("CreateManagedUser", ctx, username, password)}
}

func (_c *MockDependencytrackClient_CreateManagedUser_Call) Run(run func(ctx context.Context, username string, password string)) *MockDependencytrackClient_CreateManagedUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_CreateManagedUser_Call) Return(_a0 error) *MockDependencytrackClient_CreateManagedUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_CreateManagedUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockDependencytrackClient_CreateManagedUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOidcUser provides a mock function with given fields: ctx, email
func (_m *MockDependencytrackClient) CreateOidcUser(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_CreateOidcUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOidcUser'
type MockDependencytrackClient_CreateOidcUser_Call struct {
	*mock.Call
}

// CreateOidcUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockDependencytrackClient_Expecter) CreateOidcUser(ctx interface{}, email interface{}) *MockDependencytrackClient_CreateOidcUser_Call {
	return &MockDependencytrackClient_CreateOidcUser_Call{Call: _e.mock.On("CreateOidcUser", ctx, email)}
}

func (_c *MockDependencytrackClient_CreateOidcUser_Call) Run(run func(ctx context.Context, email string)) *MockDependencytrackClient_CreateOidcUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_CreateOidcUser_Call) Return(_a0 error) *MockDependencytrackClient_CreateOidcUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_CreateOidcUser_Call) RunAndReturn(run func(context.Context, string) error) *MockDependencytrackClient_CreateOidcUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function with given fields: ctx, name, version, group, tags
func (_m *MockDependencytrackClient) CreateProject(ctx context.Context, name string, version string, group string, tags []string) (*client.Project, error) {
	ret := _m.Called(ctx, name, version, group, tags)

	var r0 *client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) (*client.Project, error)); ok {
		return rf(ctx, name, version, group, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) *client.Project); ok {
		r0 = rf(ctx, name, version, group, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []string) error); ok {
		r1 = rf(ctx, name, version, group, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockDependencytrackClient_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version string
//   - group string
//   - tags []string
func (_e *MockDependencytrackClient_Expecter) CreateProject(ctx interface{}, name interface{}, version interface{}, group interface{}, tags interface{}) *MockDependencytrackClient_CreateProject_Call {
	return &MockDependencytrackClient_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, name, version, group, tags)}
}

func (_c *MockDependencytrackClient_CreateProject_Call) Run(run func(ctx context.Context, name string, version string, group string, tags []string)) *MockDependencytrackClient_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *MockDependencytrackClient_CreateProject_Call) Return(_a0 *client.Project, _a1 error) *MockDependencytrackClient_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_CreateProject_Call) RunAndReturn(run func(context.Context, string, string, string, []string) (*client.Project, error)) *MockDependencytrackClient_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: ctx, teamName, permissions
func (_m *MockDependencytrackClient) CreateTeam(ctx context.Context, teamName string, permissions []client.Permission) (*client.Team, error) {
	ret := _m.Called(ctx, teamName, permissions)

	var r0 *client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []client.Permission) (*client.Team, error)); ok {
		return rf(ctx, teamName, permissions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []client.Permission) *client.Team); ok {
		r0 = rf(ctx, teamName, permissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []client.Permission) error); ok {
		r1 = rf(ctx, teamName, permissions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockDependencytrackClient_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - permissions []client.Permission
func (_e *MockDependencytrackClient_Expecter) CreateTeam(ctx interface{}, teamName interface{}, permissions interface{}) *MockDependencytrackClient_CreateTeam_Call {
	return &MockDependencytrackClient_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, teamName, permissions)}
}

func (_c *MockDependencytrackClient_CreateTeam_Call) Run(run func(ctx context.Context, teamName string, permissions []client.Permission)) *MockDependencytrackClient_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]client.Permission))
	})
	return _c
}

func (_c *MockDependencytrackClient_CreateTeam_Call) Return(_a0 *client.Team, _a1 error) *MockDependencytrackClient_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_CreateTeam_Call) RunAndReturn(run func(context.Context, string, []client.Permission) (*client.Team, error)) *MockDependencytrackClient_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteManagedUser provides a mock function with given fields: ctx, username
func (_m *MockDependencytrackClient) DeleteManagedUser(ctx context.Context, username string) error {
	ret := _m.Called(ctx, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_DeleteManagedUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManagedUser'
type MockDependencytrackClient_DeleteManagedUser_Call struct {
	*mock.Call
}

// DeleteManagedUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockDependencytrackClient_Expecter) DeleteManagedUser(ctx interface{}, username interface{}) *MockDependencytrackClient_DeleteManagedUser_Call {
	return &MockDependencytrackClient_DeleteManagedUser_Call{Call: _e.mock.On("DeleteManagedUser", ctx, username)}
}

func (_c *MockDependencytrackClient_DeleteManagedUser_Call) Run(run func(ctx context.Context, username string)) *MockDependencytrackClient_DeleteManagedUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_DeleteManagedUser_Call) Return(_a0 error) *MockDependencytrackClient_DeleteManagedUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_DeleteManagedUser_Call) RunAndReturn(run func(context.Context, string) error) *MockDependencytrackClient_DeleteManagedUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOidcUser provides a mock function with given fields: ctx, username
func (_m *MockDependencytrackClient) DeleteOidcUser(ctx context.Context, username string) error {
	ret := _m.Called(ctx, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_DeleteOidcUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOidcUser'
type MockDependencytrackClient_DeleteOidcUser_Call struct {
	*mock.Call
}

// DeleteOidcUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockDependencytrackClient_Expecter) DeleteOidcUser(ctx interface{}, username interface{}) *MockDependencytrackClient_DeleteOidcUser_Call {
	return &MockDependencytrackClient_DeleteOidcUser_Call{Call: _e.mock.On("DeleteOidcUser", ctx, username)}
}

func (_c *MockDependencytrackClient_DeleteOidcUser_Call) Run(run func(ctx context.Context, username string)) *MockDependencytrackClient_DeleteOidcUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_DeleteOidcUser_Call) Return(_a0 error) *MockDependencytrackClient_DeleteOidcUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_DeleteOidcUser_Call) RunAndReturn(run func(context.Context, string) error) *MockDependencytrackClient_DeleteOidcUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function with given fields: ctx, uuid
func (_m *MockDependencytrackClient) DeleteProject(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockDependencytrackClient_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockDependencytrackClient_Expecter) DeleteProject(ctx interface{}, uuid interface{}) *MockDependencytrackClient_DeleteProject_Call {
	return &MockDependencytrackClient_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, uuid)}
}

func (_c *MockDependencytrackClient_DeleteProject_Call) Run(run func(ctx context.Context, uuid string)) *MockDependencytrackClient_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_DeleteProject_Call) Return(_a0 error) *MockDependencytrackClient_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_DeleteProject_Call) RunAndReturn(run func(context.Context, string) error) *MockDependencytrackClient_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProjects provides a mock function with given fields: ctx, name
func (_m *MockDependencytrackClient) DeleteProjects(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_DeleteProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProjects'
type MockDependencytrackClient_DeleteProjects_Call struct {
	*mock.Call
}

// DeleteProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockDependencytrackClient_Expecter) DeleteProjects(ctx interface{}, name interface{}) *MockDependencytrackClient_DeleteProjects_Call {
	return &MockDependencytrackClient_DeleteProjects_Call{Call: _e.mock.On("DeleteProjects", ctx, name)}
}

func (_c *MockDependencytrackClient_DeleteProjects_Call) Run(run func(ctx context.Context, name string)) *MockDependencytrackClient_DeleteProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_DeleteProjects_Call) Return(_a0 error) *MockDependencytrackClient_DeleteProjects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_DeleteProjects_Call) RunAndReturn(run func(context.Context, string) error) *MockDependencytrackClient_DeleteProjects_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeam provides a mock function with given fields: ctx, uuid
func (_m *MockDependencytrackClient) DeleteTeam(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type MockDependencytrackClient_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockDependencytrackClient_Expecter) DeleteTeam(ctx interface{}, uuid interface{}) *MockDependencytrackClient_DeleteTeam_Call {
	return &MockDependencytrackClient_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", ctx, uuid)}
}

func (_c *MockDependencytrackClient_DeleteTeam_Call) Run(run func(ctx context.Context, uuid string)) *MockDependencytrackClient_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_DeleteTeam_Call) Return(_a0 error) *MockDependencytrackClient_DeleteTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_DeleteTeam_Call) RunAndReturn(run func(context.Context, string) error) *MockDependencytrackClient_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserMembership provides a mock function with given fields: ctx, uuid, username
func (_m *MockDependencytrackClient) DeleteUserMembership(ctx context.Context, uuid string, username string) error {
	ret := _m.Called(ctx, uuid, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, uuid, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_DeleteUserMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserMembership'
type MockDependencytrackClient_DeleteUserMembership_Call struct {
	*mock.Call
}

// DeleteUserMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - username string
func (_e *MockDependencytrackClient_Expecter) DeleteUserMembership(ctx interface{}, uuid interface{}, username interface{}) *MockDependencytrackClient_DeleteUserMembership_Call {
	return &MockDependencytrackClient_DeleteUserMembership_Call{Call: _e.mock.On("DeleteUserMembership", ctx, uuid, username)}
}

func (_c *MockDependencytrackClient_DeleteUserMembership_Call) Run(run func(ctx context.Context, uuid string, username string)) *MockDependencytrackClient_DeleteUserMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_DeleteUserMembership_Call) Return(_a0 error) *MockDependencytrackClient_DeleteUserMembership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_DeleteUserMembership_Call) RunAndReturn(run func(context.Context, string, string) error) *MockDependencytrackClient_DeleteUserMembership_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateApiKey provides a mock function with given fields: ctx, uuid
func (_m *MockDependencytrackClient) GenerateApiKey(ctx context.Context, uuid string) (string, error) {
	ret := _m.Called(ctx, uuid)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GenerateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateApiKey'
type MockDependencytrackClient_GenerateApiKey_Call struct {
	*mock.Call
}

// GenerateApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockDependencytrackClient_Expecter) GenerateApiKey(ctx interface{}, uuid interface{}) *MockDependencytrackClient_GenerateApiKey_Call {
	return &MockDependencytrackClient_GenerateApiKey_Call{Call: _e.mock.On("GenerateApiKey", ctx, uuid)}
}

func (_c *MockDependencytrackClient_GenerateApiKey_Call) Run(run func(ctx context.Context, uuid string)) *MockDependencytrackClient_GenerateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_GenerateApiKey_Call) Return(_a0 string, _a1 error) *MockDependencytrackClient_GenerateApiKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GenerateApiKey_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockDependencytrackClient_GenerateApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigProperties provides a mock function with given fields: ctx
func (_m *MockDependencytrackClient) GetConfigProperties(ctx context.Context) ([]client.ConfigProperty, error) {
	ret := _m.Called(ctx)

	var r0 []client.ConfigProperty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.ConfigProperty, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.ConfigProperty); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ConfigProperty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GetConfigProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigProperties'
type MockDependencytrackClient_GetConfigProperties_Call struct {
	*mock.Call
}

// GetConfigProperties is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDependencytrackClient_Expecter) GetConfigProperties(ctx interface{}) *MockDependencytrackClient_GetConfigProperties_Call {
	return &MockDependencytrackClient_GetConfigProperties_Call{Call: _e.mock.On("GetConfigProperties", ctx)}
}

func (_c *MockDependencytrackClient_GetConfigProperties_Call) Run(run func(ctx context.Context)) *MockDependencytrackClient_GetConfigProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDependencytrackClient_GetConfigProperties_Call) Return(_a0 []client.ConfigProperty, _a1 error) *MockDependencytrackClient_GetConfigProperties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GetConfigProperties_Call) RunAndReturn(run func(context.Context) ([]client.ConfigProperty, error)) *MockDependencytrackClient_GetConfigProperties_Call {
	_c.Call.Return(run)
	return _c
}

// GetEcosystems provides a mock function with given fields: ctx
func (_m *MockDependencytrackClient) GetEcosystems(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GetEcosystems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEcosystems'
type MockDependencytrackClient_GetEcosystems_Call struct {
	*mock.Call
}

// GetEcosystems is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDependencytrackClient_Expecter) GetEcosystems(ctx interface{}) *MockDependencytrackClient_GetEcosystems_Call {
	return &MockDependencytrackClient_GetEcosystems_Call{Call: _e.mock.On("GetEcosystems", ctx)}
}

func (_c *MockDependencytrackClient_GetEcosystems_Call) Run(run func(ctx context.Context)) *MockDependencytrackClient_GetEcosystems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDependencytrackClient_GetEcosystems_Call) Return(_a0 []string, _a1 error) *MockDependencytrackClient_GetEcosystems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GetEcosystems_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockDependencytrackClient_GetEcosystems_Call {
	_c.Call.Return(run)
	return _c
}

// GetFindings provides a mock function with given fields: ctx, projectUuid
func (_m *MockDependencytrackClient) GetFindings(ctx context.Context, projectUuid string) ([]*client.Finding, error) {
	ret := _m.Called(ctx, projectUuid)

	var r0 []*client.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*client.Finding, error)); ok {
		return rf(ctx, projectUuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*client.Finding); ok {
		r0 = rf(ctx, projectUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GetFindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFindings'
type MockDependencytrackClient_GetFindings_Call struct {
	*mock.Call
}

// GetFindings is a helper method to define mock.On call
//   - ctx context.Context
//   - projectUuid string
func (_e *MockDependencytrackClient_Expecter) GetFindings(ctx interface{}, projectUuid interface{}) *MockDependencytrackClient_GetFindings_Call {
	return &MockDependencytrackClient_GetFindings_Call{Call: _e.mock.On("GetFindings", ctx, projectUuid)}
}

func (_c *MockDependencytrackClient_GetFindings_Call) Run(run func(ctx context.Context, projectUuid string)) *MockDependencytrackClient_GetFindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_GetFindings_Call) Return(_a0 []*client.Finding, _a1 error) *MockDependencytrackClient_GetFindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GetFindings_Call) RunAndReturn(run func(context.Context, string) ([]*client.Finding, error)) *MockDependencytrackClient_GetFindings_Call {
	_c.Call.Return(run)
	return _c
}

// GetOidcUsers provides a mock function with given fields: ctx
func (_m *MockDependencytrackClient) GetOidcUsers(ctx context.Context) ([]client.User, error) {
	ret := _m.Called(ctx)

	var r0 []client.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GetOidcUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOidcUsers'
type MockDependencytrackClient_GetOidcUsers_Call struct {
	*mock.Call
}

// GetOidcUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDependencytrackClient_Expecter) GetOidcUsers(ctx interface{}) *MockDependencytrackClient_GetOidcUsers_Call {
	return &MockDependencytrackClient_GetOidcUsers_Call{Call: _e.mock.On("GetOidcUsers", ctx)}
}

func (_c *MockDependencytrackClient_GetOidcUsers_Call) Run(run func(ctx context.Context)) *MockDependencytrackClient_GetOidcUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDependencytrackClient_GetOidcUsers_Call) Return(_a0 []client.User, _a1 error) *MockDependencytrackClient_GetOidcUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GetOidcUsers_Call) RunAndReturn(run func(context.Context) ([]client.User, error)) *MockDependencytrackClient_GetOidcUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: ctx, name, version
func (_m *MockDependencytrackClient) GetProject(ctx context.Context, name string, version string) (*client.Project, error) {
	ret := _m.Called(ctx, name, version)

	var r0 *client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.Project, error)); ok {
		return rf(ctx, name, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.Project); ok {
		r0 = rf(ctx, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockDependencytrackClient_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version string
func (_e *MockDependencytrackClient_Expecter) GetProject(ctx interface{}, name interface{}, version interface{}) *MockDependencytrackClient_GetProject_Call {
	return &MockDependencytrackClient_GetProject_Call{Call: _e.mock.On("GetProject", ctx, name, version)}
}

func (_c *MockDependencytrackClient_GetProject_Call) Run(run func(ctx context.Context, name string, version string)) *MockDependencytrackClient_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_GetProject_Call) Return(_a0 *client.Project, _a1 error) *MockDependencytrackClient_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GetProject_Call) RunAndReturn(run func(context.Context, string, string) (*client.Project, error)) *MockDependencytrackClient_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjects provides a mock function with given fields: ctx
func (_m *MockDependencytrackClient) GetProjects(ctx context.Context) ([]*client.Project, error) {
	ret := _m.Called(ctx)

	var r0 []*client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*client.Project, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*client.Project); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GetProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjects'
type MockDependencytrackClient_GetProjects_Call struct {
	*mock.Call
}

// GetProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDependencytrackClient_Expecter) GetProjects(ctx interface{}) *MockDependencytrackClient_GetProjects_Call {
	return &MockDependencytrackClient_GetProjects_Call{Call: _e.mock.On("GetProjects", ctx)}
}

func (_c *MockDependencytrackClient_GetProjects_Call) Run(run func(ctx context.Context)) *MockDependencytrackClient_GetProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDependencytrackClient_GetProjects_Call) Return(_a0 []*client.Project, _a1 error) *MockDependencytrackClient_GetProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GetProjects_Call) RunAndReturn(run func(context.Context) ([]*client.Project, error)) *MockDependencytrackClient_GetProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectsByTag provides a mock function with given fields: ctx, tag
func (_m *MockDependencytrackClient) GetProjectsByTag(ctx context.Context, tag string) ([]*client.Project, error) {
	ret := _m.Called(ctx, tag)

	var r0 []*client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*client.Project, error)); ok {
		return rf(ctx, tag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*client.Project); ok {
		r0 = rf(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GetProjectsByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectsByTag'
type MockDependencytrackClient_GetProjectsByTag_Call struct {
	*mock.Call
}

// GetProjectsByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
func (_e *MockDependencytrackClient_Expecter) GetProjectsByTag(ctx interface{}, tag interface{}) *MockDependencytrackClient_GetProjectsByTag_Call {
	return &MockDependencytrackClient_GetProjectsByTag_Call{Call: _e.mock.On("GetProjectsByTag", ctx, tag)}
}

func (_c *MockDependencytrackClient_GetProjectsByTag_Call) Run(run func(ctx context.Context, tag string)) *MockDependencytrackClient_GetProjectsByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_GetProjectsByTag_Call) Return(_a0 []*client.Project, _a1 error) *MockDependencytrackClient_GetProjectsByTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GetProjectsByTag_Call) RunAndReturn(run func(context.Context, string) ([]*client.Project, error)) *MockDependencytrackClient_GetProjectsByTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, team
func (_m *MockDependencytrackClient) GetTeam(ctx context.Context, team string) (*client.Team, error) {
	ret := _m.Called(ctx, team)

	var r0 *client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Team, error)); ok {
		return rf(ctx, team)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Team); ok {
		r0 = rf(ctx, team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockDependencytrackClient_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team string
func (_e *MockDependencytrackClient_Expecter) GetTeam(ctx interface{}, team interface{}) *MockDependencytrackClient_GetTeam_Call {
	return &MockDependencytrackClient_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, team)}
}

func (_c *MockDependencytrackClient_GetTeam_Call) Run(run func(ctx context.Context, team string)) *MockDependencytrackClient_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_GetTeam_Call) Return(_a0 *client.Team, _a1 error) *MockDependencytrackClient_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*client.Team, error)) *MockDependencytrackClient_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeams provides a mock function with given fields: ctx
func (_m *MockDependencytrackClient) GetTeams(ctx context.Context) ([]client.Team, error) {
	ret := _m.Called(ctx)

	var r0 []client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_GetTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeams'
type MockDependencytrackClient_GetTeams_Call struct {
	*mock.Call
}

// GetTeams is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDependencytrackClient_Expecter) GetTeams(ctx interface{}) *MockDependencytrackClient_GetTeams_Call {
	return &MockDependencytrackClient_GetTeams_Call{Call: _e.mock.On("GetTeams", ctx)}
}

func (_c *MockDependencytrackClient_GetTeams_Call) Run(run func(ctx context.Context)) *MockDependencytrackClient_GetTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDependencytrackClient_GetTeams_Call) Return(_a0 []client.Team, _a1 error) *MockDependencytrackClient_GetTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_GetTeams_Call) RunAndReturn(run func(context.Context) ([]client.Team, error)) *MockDependencytrackClient_GetTeams_Call {
	_c.Call.Return(run)
	return _c
}

// Headers provides a mock function with given fields: ctx
func (_m *MockDependencytrackClient) Headers(ctx context.Context) (http.Header, error) {
	ret := _m.Called(ctx)

	var r0 http.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (http.Header, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) http.Header); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_Headers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Headers'
type MockDependencytrackClient_Headers_Call struct {
	*mock.Call
}

// Headers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDependencytrackClient_Expecter) Headers(ctx interface{}) *MockDependencytrackClient_Headers_Call {
	return &MockDependencytrackClient_Headers_Call{Call: _e.mock.On("Headers", ctx)}
}

func (_c *MockDependencytrackClient_Headers_Call) Run(run func(ctx context.Context)) *MockDependencytrackClient_Headers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDependencytrackClient_Headers_Call) Return(_a0 http.Header, _a1 error) *MockDependencytrackClient_Headers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_Headers_Call) RunAndReturn(run func(context.Context) (http.Header, error)) *MockDependencytrackClient_Headers_Call {
	_c.Call.Return(run)
	return _c
}

// PortfolioRefresh provides a mock function with given fields: ctx
func (_m *MockDependencytrackClient) PortfolioRefresh(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_PortfolioRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PortfolioRefresh'
type MockDependencytrackClient_PortfolioRefresh_Call struct {
	*mock.Call
}

// PortfolioRefresh is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDependencytrackClient_Expecter) PortfolioRefresh(ctx interface{}) *MockDependencytrackClient_PortfolioRefresh_Call {
	return &MockDependencytrackClient_PortfolioRefresh_Call{Call: _e.mock.On("PortfolioRefresh", ctx)}
}

func (_c *MockDependencytrackClient_PortfolioRefresh_Call) Run(run func(ctx context.Context)) *MockDependencytrackClient_PortfolioRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDependencytrackClient_PortfolioRefresh_Call) Return(_a0 error) *MockDependencytrackClient_PortfolioRefresh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_PortfolioRefresh_Call) RunAndReturn(run func(context.Context) error) *MockDependencytrackClient_PortfolioRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAdminUsers provides a mock function with given fields: ctx, users
func (_m *MockDependencytrackClient) RemoveAdminUsers(ctx context.Context, users *client.AdminUsers) error {
	ret := _m.Called(ctx, users)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.AdminUsers) error); ok {
		r0 = rf(ctx, users)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_RemoveAdminUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAdminUsers'
type MockDependencytrackClient_RemoveAdminUsers_Call struct {
	*mock.Call
}

// RemoveAdminUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - users *client.AdminUsers
func (_e *MockDependencytrackClient_Expecter) RemoveAdminUsers(ctx interface{}, users interface{}) *MockDependencytrackClient_RemoveAdminUsers_Call {
	return &MockDependencytrackClient_RemoveAdminUsers_Call{Call: _e.mock.On("RemoveAdminUsers", ctx, users)}
}

func (_c *MockDependencytrackClient_RemoveAdminUsers_Call) Run(run func(ctx context.Context, users *client.AdminUsers)) *MockDependencytrackClient_RemoveAdminUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.AdminUsers))
	})
	return _c
}

func (_c *MockDependencytrackClient_RemoveAdminUsers_Call) Return(_a0 error) *MockDependencytrackClient_RemoveAdminUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_RemoveAdminUsers_Call) RunAndReturn(run func(context.Context, *client.AdminUsers) error) *MockDependencytrackClient_RemoveAdminUsers_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerAnalysis provides a mock function with given fields: ctx, projectUuid
func (_m *MockDependencytrackClient) TriggerAnalysis(ctx context.Context, projectUuid string) error {
	ret := _m.Called(ctx, projectUuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, projectUuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_TriggerAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerAnalysis'
type MockDependencytrackClient_TriggerAnalysis_Call struct {
	*mock.Call
}

// TriggerAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - projectUuid string
func (_e *MockDependencytrackClient_Expecter) TriggerAnalysis(ctx interface{}, projectUuid interface{}) *MockDependencytrackClient_TriggerAnalysis_Call {
	return &MockDependencytrackClient_TriggerAnalysis_Call{Call: _e.mock.On("TriggerAnalysis", ctx, projectUuid)}
}

func (_c *MockDependencytrackClient_TriggerAnalysis_Call) Run(run func(ctx context.Context, projectUuid string)) *MockDependencytrackClient_TriggerAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDependencytrackClient_TriggerAnalysis_Call) Return(_a0 error) *MockDependencytrackClient_TriggerAnalysis_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_TriggerAnalysis_Call) RunAndReturn(run func(context.Context, string) error) *MockDependencytrackClient_TriggerAnalysis_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: ctx, uuid, name, version, group, tags
func (_m *MockDependencytrackClient) UpdateProject(ctx context.Context, uuid string, name string, version string, group string, tags []string) (*client.Project, error) {
	ret := _m.Called(ctx, uuid, name, version, group, tags)

	var r0 *client.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, []string) (*client.Project, error)); ok {
		return rf(ctx, uuid, name, version, group, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, []string) *client.Project); ok {
		r0 = rf(ctx, uuid, name, version, group, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, []string) error); ok {
		r1 = rf(ctx, uuid, name, version, group, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockDependencytrackClient_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - name string
//   - version string
//   - group string
//   - tags []string
func (_e *MockDependencytrackClient_Expecter) UpdateProject(ctx interface{}, uuid interface{}, name interface{}, version interface{}, group interface{}, tags interface{}) *MockDependencytrackClient_UpdateProject_Call {
	return &MockDependencytrackClient_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, uuid, name, version, group, tags)}
}

func (_c *MockDependencytrackClient_UpdateProject_Call) Run(run func(ctx context.Context, uuid string, name string, version string, group string, tags []string)) *MockDependencytrackClient_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].([]string))
	})
	return _c
}

func (_c *MockDependencytrackClient_UpdateProject_Call) Return(_a0 *client.Project, _a1 error) *MockDependencytrackClient_UpdateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_UpdateProject_Call) RunAndReturn(run func(context.Context, string, string, string, string, []string) (*client.Project, error)) *MockDependencytrackClient_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProjectInfo provides a mock function with given fields: ctx, uuid, version, group, tags
func (_m *MockDependencytrackClient) UpdateProjectInfo(ctx context.Context, uuid string, version string, group string, tags []string) error {
	ret := _m.Called(ctx, uuid, version, group, tags)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) error); ok {
		r0 = rf(ctx, uuid, version, group, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_UpdateProjectInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProjectInfo'
type MockDependencytrackClient_UpdateProjectInfo_Call struct {
	*mock.Call
}

// UpdateProjectInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - version string
//   - group string
//   - tags []string
func (_e *MockDependencytrackClient_Expecter) UpdateProjectInfo(ctx interface{}, uuid interface{}, version interface{}, group interface{}, tags interface{}) *MockDependencytrackClient_UpdateProjectInfo_Call {
	return &MockDependencytrackClient_UpdateProjectInfo_Call{Call: _e.mock.On("UpdateProjectInfo", ctx, uuid, version, group, tags)}
}

func (_c *MockDependencytrackClient_UpdateProjectInfo_Call) Run(run func(ctx context.Context, uuid string, version string, group string, tags []string)) *MockDependencytrackClient_UpdateProjectInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *MockDependencytrackClient_UpdateProjectInfo_Call) Return(_a0 error) *MockDependencytrackClient_UpdateProjectInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_UpdateProjectInfo_Call) RunAndReturn(run func(context.Context, string, string, string, []string) error) *MockDependencytrackClient_UpdateProjectInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UploadProject provides a mock function with given fields: ctx, name, version, bom
func (_m *MockDependencytrackClient) UploadProject(ctx context.Context, name string, version string, bom []byte) error {
	ret := _m.Called(ctx, name, version, bom)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, name, version, bom)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDependencytrackClient_UploadProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadProject'
type MockDependencytrackClient_UploadProject_Call struct {
	*mock.Call
}

// UploadProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version string
//   - bom []byte
func (_e *MockDependencytrackClient_Expecter) UploadProject(ctx interface{}, name interface{}, version interface{}, bom interface{}) *MockDependencytrackClient_UploadProject_Call {
	return &MockDependencytrackClient_UploadProject_Call{Call: _e.mock.On("UploadProject", ctx, name, version, bom)}
}

func (_c *MockDependencytrackClient_UploadProject_Call) Run(run func(ctx context.Context, name string, version string, bom []byte)) *MockDependencytrackClient_UploadProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockDependencytrackClient_UploadProject_Call) Return(_a0 error) *MockDependencytrackClient_UploadProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDependencytrackClient_UploadProject_Call) RunAndReturn(run func(context.Context, string, string, []byte) error) *MockDependencytrackClient_UploadProject_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with given fields: ctx
func (_m *MockDependencytrackClient) Version(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDependencytrackClient_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockDependencytrackClient_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDependencytrackClient_Expecter) Version(ctx interface{}) *MockDependencytrackClient_Version_Call {
	return &MockDependencytrackClient_Version_Call{Call: _e.mock.On("Version", ctx)}
}

func (_c *MockDependencytrackClient_Version_Call) Run(run func(ctx context.Context)) *MockDependencytrackClient_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDependencytrackClient_Version_Call) Return(_a0 string, _a1 error) *MockDependencytrackClient_Version_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDependencytrackClient_Version_Call) RunAndReturn(run func(context.Context) (string, error)) *MockDependencytrackClient_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDependencytrackClient creates a new instance of MockDependencytrackClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expect.
// The first argument is typically a *testing.T value.
func NewMockDependencytrackClient(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockDependencytrackClient {
	mock := &MockDependencytrackClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
