package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/nais/console-backend/internal/graph/model"
)

// Cost is the resolver for the cost field.
func (r *queryResolver) Cost(ctx context.Context, filter *model.CostFilter) (*model.Cost, error) {
	panic(fmt.Errorf("not implemented: Cost - cost"))
}
