package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/nais/console-backend/internal/graph/model"
	"github.com/nais/console-backend/internal/graph/scalar"
)

// VulnerabilitiesForTeam is the resolver for the vulnerabilitiesForTeam field.
func (r *queryResolver) VulnerabilitiesForTeam(ctx context.Context, team string, first *int, last *int, after *scalar.Cursor, before *scalar.Cursor, orderBy *model.AppsOrderBy) ([]*model.DependencyTrack, error) {
	/*if orderBy != nil {
		apps = model.NewSortableApps(apps, orderBy).Sort()
	}*/

	panic(fmt.Errorf("not implemented: VulnerabilitiesForTeam - vulnerabilitiesForTeam"))
}
