package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/nais/console-backend/internal/graph/model"
	"github.com/nais/console-backend/internal/hookd"
)

// Deployments is the resolver for the deployments field.
func (r *queryResolver) Deployments(ctx context.Context, offset *int, limit *int) (*model.DeploymentList, error) {
	l := 100
	if limit != nil {
		l = *limit
	}
	deploys, err := r.hookdClient.Deployments(ctx, hookd.WithLimit(l), hookd.WithIgnoreTeams("nais-verification"))
	if err != nil {
		return nil, fmt.Errorf("getting deploys from Hookd: %w", err)
	}

	pagination := model.NewPagination(offset, limit)
	n, pi := model.PaginatedSlice(deploys, pagination)

	return &model.DeploymentList{
		Nodes:    deployToModel(n),
		PageInfo: pi,
	}, nil
}
