package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/nais/console-backend/internal/graph/model"
	"github.com/nais/console-backend/internal/hookd"
)

// History is the resolver for the history field.
func (r *deployInfoResolver) History(ctx context.Context, obj *model.DeployInfo, offset *int, limit *int) (model.DeploymentResponse, error) {
	name := obj.GQLVars.App
	kind := "Application"
	if obj.GQLVars.Job != "" {
		kind = "Naisjob"
		name = obj.GQLVars.Job
	}

	deploys, err := r.hookdClient.Deployments(ctx, hookd.WithTeam(obj.GQLVars.Team), hookd.WithCluster(obj.GQLVars.Env))
	if err != nil {
		return nil, fmt.Errorf("getting deploys from Hookd: %w", err)
	}

	deploys = filterDeploysByNameAndKind(deploys, name, kind)

	pagination := model.NewPagination(offset, limit)
	n, pi := model.PaginatedSlice(deploys, pagination)

	return &model.DeploymentList{
		Nodes:    deployToModel(n),
		PageInfo: pi,
	}, nil
}

// DeployInfo returns DeployInfoResolver implementation.
func (r *Resolver) DeployInfo() DeployInfoResolver { return &deployInfoResolver{r} }

type deployInfoResolver struct{ *Resolver }
