package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/nais/console-backend/internal/graph/model"
)

// FindTeamBySlug is the resolver for the findTeamBySlug field.
func (r *entityResolver) FindTeamBySlug(ctx context.Context, slug string) (*model.Team, error) {
	panic(fmt.Errorf("not implemented: FindTeamBySlug - findTeamBySlug"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
