package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"github.com/nais/console-backend/internal/graph/model"
)

// JobInstances is the resolver for the jobInstances field.
func (r *jobResolver) JobInstances(ctx context.Context, obj *model.Job) ([]*model.JobInstance, error) {
	jobInstances, err := r.K8s.JobInstances(ctx, obj.GQLVars.Team, obj.Env.Name, obj.Name)
	if err != nil {
		return nil, fmt.Errorf("getting job instances from Kubernetes: %w", err)
	}

	return jobInstances, nil
}

// Manifest is the resolver for the manifest field.
func (r *jobResolver) Manifest(ctx context.Context, obj *model.Job) (string, error) {
	job, err := r.K8s.JobManifest(ctx, obj.Name, obj.GQLVars.Team, obj.Env.Name)
	if err != nil {
		return "", fmt.Errorf("getting job manifest from Kubernetes: %w", err)
	}
	return job, err
}

// Team is the resolver for the team field.
func (r *jobResolver) Team(ctx context.Context, obj *model.Job) (*model.Team, error) {
	return r.TeamsClient.GetTeam(ctx, obj.GQLVars.Team)
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, name string, team string, env string) (*model.Job, error) {
	job, err := r.K8s.Job(ctx, name, team, env)
	if err != nil {
		return nil, fmt.Errorf("getting job from Kubernetes: %w", err)
	}
	return job, nil
}

// Job returns JobResolver implementation.
func (r *Resolver) Job() JobResolver { return &jobResolver{r} }

type jobResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *jobResolver) Instances(ctx context.Context, obj *model.Job) ([]*model.JobInstance, error) {
	panic(fmt.Errorf("not implemented: Instances - instances"))
}
