package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/nais/console-backend/internal/graph/model"
)

// Log is the resolver for the log field.
func (r *subscriptionResolver) Log(ctx context.Context, input *model.LogSubscriptionInput) (<-chan *model.LogLine, error) {

	return r.K8s.LogStream(ctx, input.Env, input.Team, input.App, input.Instances)
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
