package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"

	"github.com/nais/console-backend/internal/graph/model"
	"github.com/nais/console-backend/internal/search"
)

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string) (*model.SearchConnection, error) {
	edges := r.Searcher.Search(ctx, query, search.Filters{})
	return &model.SearchConnection{Edges: edges}, nil
}
